format = """
$directory\
[ ](fg:#87af5f bg:#394260)\
$git_branch\
[ ](fg:#394260)\
"""

add_newline = false

[directory]
style = "fg:#e3e5e5 bg:#87af5f"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#87af5f bg:#394260)]($style)'
