#!/bin/bash

cp shell/.bashrc ~/
cp shell/.bash_profile ~/
cp shell/starship.toml ~/.config/starship.toml
cp shell/.deltagitconfig ~/

# For some reason, neodev.nvim requires this directory to be present to load the vim symbols into
# the LSP. I don't understand why!
mkdir -p ~/.config/nvim/lua
cp editor/init.lua ~/.config/nvim/

cp terminal/.tmux.conf ~/
